[package]
name = "r6502"
version = "0.1.0"
description = "6502 emulator"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "1.3"
num-traits = "0.2"
byteorder = "1.4"
hxdmp = "0.2"
clap = { version = "4.0", features = ["derive"] }
